### ISSUE TITLE
Update Diesel Crate to 1.0 (beta)

### ISSUE THREAD

**Issue by lawliet89** [lawliet89/rowdy#82]
https://github.com/diesel-rs/diesel/releases/tag/v1.0.0-beta1

**Comment by piedoom** [comment]
I wasn't sure if this crate was maintained, so I tried to [take a stab](https://github.com/resamplr/rowdy).  It's not working yet but it doesn't seem like a horribly difficult task.  I am getting some errors that I'm having trouble with, though.

**Comment by lawliet89** [comment]
I've not had time to work on this in a while.

Can you post some of the errors? Might be worth taking look at the [changelog](https://github.com/diesel-rs/diesel/blob/v1.1.1/CHANGELOG.md) to see what breaking changes have been made.

**Comment by piedoom** [comment]
That's a great idea - I'll take a look at it later tonight and tomorrow, and post issues if I run into any.

**Comment by lawliet89** [comment]
I have updated the crate to the latest version of Diesel (1.4.2). Please reopen an issue if it still does not work.

**Comment by piedoom** [comment]
Fantastic news! Thank you.
