### ISSUE TITLE
rowdy and Docker Registry

### ISSUE THREAD

**Issue by codingfrombrazil** [lawliet89/rowdy#83]
Since it's based on Docker Registry's authentication protocol, I think I can put rowdy in front of Docker Registry in order to provide authentication, right? (Maybe I'm missing something.)

**Comment by lawliet89** [comment]
It's not exactly the same protocol.

You should use https://github.com/cesanta/docker_auth instead.

**Comment by codingfrombrazil** [comment]
Oh I see.. Thank you for answering. xD
