### ISSUE TITLE
Examples on integration

### ISSUE THREAD

**Issue by piedoom** [lawliet89/rowdy#85]
Hey there, 
apologies for the noobish question - are there examples somewhere on how this might be integrated into an existing project?

**Comment by lawliet89** [comment]
What sort of integration do you mean?

To run `rowdy`, you can go into the `cli` directory and do a `cargo run`. Use `cargo run -- --help` for more information.

If you are referring to how applications can use authentication with Rowdy, you can read more about it in the [docs](https://docs.rs/rowdy/0.0.9/rowdy/#authentication-flow).

**Comment by piedoom** [comment]
For instance, I have an API with which I would like authentication.  In my specific case (just as an idea of why this may be useful) I wasn't sure whether - for instance - whether rowdy should be run as a separate service, or integrated as a library in my backend source. This may just be due to lack of knowledge on my part, however.

I think docs are great, but having actual code examples of real-world instances is also a great way to learn. For instance, what does a minimal rowdy setup with a diesel site look like, and how should it be structured in a real application?

**Comment by lawliet89** [comment]
The whole point of JWT authentication is to be stateless and for applications to not have to talk to the authentication server at all.  Thus, the best way, imo, is to run rowdy as a separate authentication service that you direct your clients to authenticate with. Then, once they get a JWT from rowdy, then can present the JWT to your API applications for authentication.

Rowdy doesn't really care where your users come from, nor does it attempt to manage your users. So, if you want to use Diesel to source the list of users from a database, you would either have to extend the rowdy CLI to add user management features (not recommended) or to simply manage the users in a separate application/service.

**Comment by piedoom** [comment]
OK! Thank you.
